### ISSUE TITLE
Add Category

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/ar.com.tuxguitar.TuxGuitar#1]
![Captura de tela de 2019-05-15 22-43-03](https://user-images.githubusercontent.com/26097419/57820366-de349880-7762-11e9-8b1b-2b63e745360c.png)

**Comment by gabops** [comment]
Where do I need to define that?

**Comment by LeandroStanger** [comment]
appdata.xml

**Comment by gabops** [comment]
Thank you so much for your PR.
