### ISSUE TITLE
Old version on flathub (1.5.2 -> 1.5.3)

### ISSUE THREAD

**Issue by christianfl** [flathub/ar.com.tuxguitar.TuxGuitar#12]
Hey guys! The tuxguitar version on flathub is outdated. On 12. of December version 1.5.3 has been released. See https://sourceforge.net/projects/tuxguitar/files/TuxGuitar/TuxGuitar-1.5.3/

**Comment by nedrichards** [comment]
Fixed by https://github.com/flathub/ar.com.tuxguitar.TuxGuitar/pull/11
