### ISSUE TITLE
Changes to plugins are not saved

### ISSUE THREAD

**Issue by Gert-dev** [flathub/ar.com.tuxguitar.TuxGuitar#22]
Hello

I'm trying to enable the Java Sound Api plugin from the Plugins menu, but each time I restart TuxGuitar, it disables itself again. The same happens when I disable a plugin, it reenables itself. Is it possible that plugin state isn't stored properly?

This could also be a TuxGuitar bug, but I don't recall this happening with the non-Flatpak version.

Thanks!

**Comment by hfiguiere** [comment]
where are these supposed to be stored? Given that the flaptak already have very broad filesystem permissions..... (`host`)

**Comment by Gert-dev** [comment]
Oops, it looks like I disabled the `--filesystem=host` permissions a long time ago and forgot about it. Re-enabling them fixes it. Sorry about that, and thanks!

Now that you mention it, though: is there is a reason the permissions are so broad? IIRC full host filesystem permissions are recommended against for Flatpaks since they poke a large hole in the sandbox. FWIW, I can also get the preferences to save properly by just adding `.tuxguitar-1.5.6` to the persistent paths (not the filesystem ones, as this folder just needs to be persisted, not necessarily passed through), and disabling host filesystem permissions.

**Comment by hfiguiere** [comment]
Probably because the reviewers back then were less strict. Or the maintainer before me.

I'm willing to close them up, but that's something that is not friction less as it might break for users.

(yes I'm all for making it less broad)

**Comment by Gert-dev** [comment]
That is true. Maybe it would be good to start incrementally; a good first step might be to switch from full host filesystem permissions to home folder permissions, which will not break anything for most users, assuming most users are interacting with their own music files inside their home folder. One could go further and switch to `xdg-documents` and/or `xdg-music`, which are probably the most relevant to TuxGuitar.

Of course in an ideal world, TuxGuitar would use the FileChooser portal so the user can select pretty much any file, whilst still not giving TuxGuitar access to anything without the user selecting it first, but I don't see that happening any time soon.

**Comment by hfiguiere** [comment]
I consider the matter resolved.

**Comment by hfiguiere** [comment]
and as an aside I just lowered to the filesystem permissions to restrict to home.
