### ISSUE TITLE
Stuck on splash screen since update to 1.6.2 (probably Wayland issue)

### ISSUE THREAD

**Issue by Gert-dev** [flathub/ar.com.tuxguitar.TuxGuitar#35]
Since the update to 1.6.2 recently, I can't get TuxGuitar to start any more. It's likely https://github.com/helge17/tuxguitar/issues/323 since I have the same error logs. The proposed fix is to update to a pre-release, apparently.

**Comment by lorecapob** [comment]
Same error here with 1.6.2. For the moment, I just downgraded to the last commit (version 1.5.6) since it works fine.

OS: Fedora 40 Workstation on Wayland

**Comment by hfiguiere** [comment]
works here on Fedora SB 40, wayland of course.

**Comment by hfiguiere** [comment]
And works on Fedora 39 workstation wayland AMD this time

**Comment by hfiguiere** [comment]
Also 1.5.6 is X11 only at the flatpak level.

**Comment by hfiguiere** [comment]
but if the splash is up my money is not a wayland issue (otherwise you'd see nothing). But on the audio.

**Comment by guiv42** [comment]
> The proposed fix is to update to a pre-release, apparently

It just means that *if* your problem *is* https://github.com/helge17/tuxguitar/issues/323 then it will be fixed in next release. No release date planned yet, it's currently being discussed.

**Comment by guiv42** [comment]
Could someone test this in an appropriate environment? Logically issue should have been fixed by #37

**Comment by lorecapob** [comment]
Updated to 1.6.3 this morning. There is no longer any problem starting the application and it seems to work fine, thank you

OS: Fedora 40 Workstation on Wayland

**Comment by Gert-dev** [comment]
I can confirm this is fixed for me too, I'll close, thanks!
