### ISSUE TITLE
UI too small on HiDPI screen

### ISSUE THREAD

**Issue by hfiguiere** [flathub/ar.com.tuxguitar.TuxGuitar#6]
TuxGuitar UI is too small on HiDPI.

Since it uses Qt4, there is no work around. But with Qt5 it should be workable.

The other alternative is to use the swt version labeled as `GNU/Linux-x86_64 Binary Files` on the download page. This is what Fedora ships and it works.

Here is the screenshot

![Screenshot from 2019-06-06 00-33-47](https://user-images.githubusercontent.com/114441/59007060-ee381900-87f2-11e9-8dd8-ad5480bb494a.png)

**Comment by gabops** [comment]
Thanks for opening this issue. I will test your suggestion and if everything looks good update the manifest ASAP.

**Comment by gabops** [comment]
@hfiguiere I have a PR ready with some improvements and one of them is the change to jwt instead of qt4 (https://github.com/flathub/ar.com.tuxguitar.TuxGuitar/pull/5). I've tested it and looks good but would be very helpful if you can give it a try for being sure it works as expected (build 4617).

**Comment by gabops** [comment]
The changes have been tested and merged to master. This issue can be closed.
