### ISSUE TITLE
Incorrect metadata (version, last update)

### ISSUE THREAD

**Issue by contactobscurantist** [flathub/ar.com.tuxguitar.TuxGuitar#7]
Currently, metadata on flathub states _version_ 1.5 and _Last Update_ on 02.02.2018.
`flatpak info ar.com.tuxguitar.TuxGuitar`
properly shows last update as 2019-06-20, but also displays version as 1.5 while TuxGuitar's own "Help -> About" displays version 1.5.2.

With the flatpak version seeing improvment, keeping old values is too modest!
Also, is **appdata.xml** being updated only manually, or is it generated automatically?

**Comment by TingPing** [comment]
Appdata is manually kept in sync. Feel free to correct it.
